const bands = {
    "band_0001": {
        "actname": "Pyramid Scheme",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Atmospheric Instrumental Rock",
        "image": "",
        "_id": "band_0001"
    },
    "band_0002": {
        "actname": "Doñ Swayze",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Americana Rock",
        "image": "",
        "_id": "band_0002"
    },
    "band_0003": {
        "actname": "Lateral Collateral",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Classic and Alt Rock",
        "image": "",
        "_id": "band_0003"
    },
    "band_0004": {
        "actname": "13 Down Below",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Chicago and Modern Blues",
        "image": "",
        "_id": "band_0004"
    },
    "band_0005": {
        "actname": "The Local Enigma",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Psychedelic, Unique, Kickass",
        "image": "",
        "_id": "band_0005"
    },
    "band_0006": {
        "actname": "Roundabouts",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Beat Goes Round",
        "image": "",
        "_id": "band_0006"
    },
    "band_0007": {
        "actname": "Don't Call Me Lizz + Ethan Franklin and Friends",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Alternative Pop Rock",
        "image": "",
        "_id": "band_0007"
    },
    "band_0008": {
        "actname": "The Martones (aka Tom Marton and Friends)",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Pop/Swing/Rock",
        "image": "",
        "_id": "band_0008"
    },
    "band_0009": {
        "actname": "Morningside Messengers",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Energetic, Groovy, Fun",
        "image": "",
        "_id": "band_0009"
    },
    "band_0010": {
        "actname": "Oak.Land",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Dance Pop Rap",
        "image": "",
        "_id": "band_0010"
    },
    "band_0011": {
        "actname": "Usually Seven",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "",
        "image": "",
        "_id": "band_0011"
    },
    "band_0012": {
        "actname": "Sweetbrier",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Traditional Folk Americana",
        "image": "",
        "_id": "band_0012"
    },
    "band_0013": {
        "actname": "A Big Hat",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "A Big Hat",
        "image": "",
        "_id": "band_0013"
    },
    "band_0014": {
        "actname": "CCB-Sides",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Soulful, Acoustic, Spirited",
        "image": "",
        "_id": "band_0014"
    },
    "band_0015": {
        "actname": "Boston Modular Meetup",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Ambient Electronic Music",
        "image": "",
        "_id": "band_0015"
    },
    "band_0016": {
        "actname": "Amory",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Indie Folk Rock",
        "image": "",
        "_id": "band_0016"
    },
    "band_0017": {
        "actname": "Roam Kid Roam",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Soul-Food Folk",
        "image": "",
        "_id": "band_0017"
    },
    "band_0018": {
        "actname": "Polar Vortex",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Horn Driven Jazz",
        "image": "",
        "_id": "band_0018"
    },
    "band_0019": {
        "actname": "Corinna Parrish",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Introspective Fruit Rock",
        "image": "",
        "_id": "band_0019"
    },
    "band_0020": {
        "actname": "The Wiggly Tendrils",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Chamber Pop Songs",
        "image": "",
        "_id": "band_0020"
    },
    "band_0021": {
        "actname": "Granite City Stoop Strummers",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Acoustic Americana",
        "image": "",
        "_id": "band_0021"
    },
    "band_0022": {
        "actname": "Glanzer Mar",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Honest. Dynamic. Nostalgic.",
        "image": "",
        "_id": "band_0022"
    },
    "band_0023": {
        "actname": "Adults",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Allston Rock, Mellow",
        "image": "",
        "_id": "band_0023"
    },
    "band_0024": {
        "actname": "Aiden Kawada",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Songwriter, Vocalist, Producer",
        "image": "",
        "_id": "band_0024"
    },
    "band_0025": {
        "actname": "No Idea",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Pop RnB Jams",
        "image": "",
        "_id": "band_0025"
    },
    "band_0026": {
        "actname": "Mike Sempert",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Indie Rock",
        "image": "",
        "_id": "band_0026"
    },
    "band_0027": {
        "actname": "Blinn & The Breakdown",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "2000s Alt Pop",
        "image": "",
        "_id": "band_0027"
    },
    "band_0028": {
        "actname": "Tusken and the Raiders",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Pop Rock Funk",
        "image": "",
        "_id": "band_0028"
    },
    "band_0029": {
        "actname": "State Parque",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Indie Surf Rock",
        "image": "",
        "_id": "band_0029"
    },
    "band_0030": {
        "actname": "washaway",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Gloomy Indie Electronic",
        "image": "",
        "_id": "band_0030"
    },
    "band_0031": {
        "actname": "Dog Town",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Energetic, Eclectic, Accessible",
        "image": "",
        "_id": "band_0031"
    },
    "band_0032": {
        "actname": "John Lebanon",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Dynamic Indie Folk",
        "image": "",
        "_id": "band_0032"
    },
    "band_0033": {
        "actname": "Ukulele Summers",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "",
        "image": "",
        "_id": "band_0033"
    },
    "band_0034": {
        "actname": "The After Jam",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Ukulele Jazz Ensemble",
        "image": "",
        "_id": "band_0034"
    },
    "band_0035": {
        "actname": "Johanna",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Powerful Emotional Loud",
        "image": "",
        "_id": "band_0035"
    },
    "band_0036": {
        "actname": "Mike Barrasso",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Natural. Energetic. Smooth",
        "image": "",
        "_id": "band_0036"
    },
    "band_0037": {
        "actname": "Cami & Logan",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Soulful, Acoustic, Technical",
        "image": "",
        "_id": "band_0037"
    },
    "band_0038": {
        "actname": "Similar Jones",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "High-Energy Vocal Band",
        "image": "",
        "_id": "band_0038"
    },
    "band_0039": {
        "actname": "RnB3",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jazzy Bluesy R&B",
        "image": "",
        "_id": "band_0039"
    },
    "band_0040": {
        "actname": "MotherPlucker Brothers",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Acoustic Rockin' Folk",
        "image": "",
        "_id": "band_0040"
    },
    "band_0041": {
        "actname": "Target Practice",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Energetic Girl Band",
        "image": "",
        "_id": "band_0041"
    },
    "band_0042": {
        "actname": "Not Dead Yet",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Rock/Alt-Rock Cover Band",
        "image": "",
        "_id": "band_0042"
    },
    "band_0043": {
        "actname": "Mémé",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Witty, Upbeat, Passionate",
        "image": "",
        "_id": "band_0043"
    },
    "band_0044": {
        "actname": "The C-Section",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Chaotic, Groovy, Joyful",
        "image": "",
        "_id": "band_0044"
    },
    "band_0045": {
        "actname": "Collective Measures A Capella.",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "A Cappella Group",
        "image": "",
        "_id": "band_0045"
    },
    "band_0046": {
        "actname": "The Heather Mumford Project",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Country, Blues, Americana",
        "image": "",
        "_id": "band_0046"
    },
    "band_0047": {
        "actname": "Gliss Girls",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Minimalist Thrift Pop",
        "image": "",
        "_id": "band_0047"
    },
    "band_0048": {
        "actname": "The Double Lives",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Creative. Energetic. Rock.",
        "image": "",
        "_id": "band_0048"
    },
    "band_0049": {
        "actname": "Orquestro do Gigantes Vermelho (Red Giant Orchestra)",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Brazilian Choro Ensemble",
        "image": "",
        "_id": "band_0049"
    },
    "band_0050": {
        "actname": "Billboard Top Folksy",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Pop Favorites, Acousticized",
        "image": "",
        "_id": "band_0050"
    },
    "band_0051": {
        "actname": "PJ Childs",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Nostalgic, Honest, Warm",
        "image": "",
        "_id": "band_0051"
    },
    "band_0052": {
        "actname": "Craig Sonnenfeld",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Singer-Songwriter, Guitarist.",
        "image": "",
        "_id": "band_0052"
    },
    "band_0053": {
        "actname": "Junko Ogawa & Frank Albani with special guest Branson Bofat",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Classic Rock Duo",
        "image": "",
        "_id": "band_0053"
    },
    "band_0054": {
        "actname": "Benjamin Fortier",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Ambient Post-Rock",
        "image": "",
        "_id": "band_0054"
    },
    "band_0055": {
        "actname": "The Newtalians",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Italian Songs Reimagined.",
        "image": "",
        "_id": "band_0055"
    },
    "band_0056": {
        "actname": "Jenny Jumpstart",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Original, Indie, Country",
        "image": "",
        "_id": "band_0056"
    },
    "band_0057": {
        "actname": "Lemonshiners",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Homespun Psychedelic Bluegrass",
        "image": "",
        "_id": "band_0057"
    },
    "band_0058": {
        "actname": "Flamenco",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Dance, Guitar, Song",
        "image": "",
        "_id": "band_0058"
    },
    "band_0059": {
        "actname": "The Beacons",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Classic Rock Across 4 Decades",
        "image": "",
        "_id": "band_0059"
    },
    "band_0060": {
        "actname": "Tracy Jack Reed",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "",
        "image": "",
        "_id": "band_0060"
    },
    "band_0061": {
        "actname": "The Sharp Nines",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jazz. Horns. Power.",
        "image": "",
        "_id": "band_0061"
    },
    "band_0062": {
        "actname": "filet of soul",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Finding Our Groove",
        "image": "",
        "_id": "band_0062"
    },
    "band_0063": {
        "actname": "The Kelliher's",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun, Friendly, Unique",
        "image": "",
        "_id": "band_0063"
    },
    "band_0064": {
        "actname": "Charlie & Friends",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun for All!",
        "image": "",
        "_id": "band_0064"
    },
    "band_0065": {
        "actname": "The Strummerville Ukulele Club",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Ukulele Joy!",
        "image": "",
        "_id": "band_0065"
    },
    "band_0066": {
        "actname": "Eva Ullmann",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Powerhouse, Bubbly, Dynamic",
        "image": "",
        "_id": "band_0066"
    },
    "band_0067": {
        "actname": "Grateful Dads",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Classic Rock Jams",
        "image": "",
        "_id": "band_0067"
    },
    "band_0068": {
        "actname": "Asamuri",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jrock Cover Band",
        "image": "",
        "_id": "band_0068"
    },
    "band_0069": {
        "actname": "Sym_DJ",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Queer Alternative Groove and Dance",
        "image": "",
        "_id": "band_0069"
    },
    "band_0070": {
        "actname": "SOULO",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Queer Rock Indie",
        "image": "",
        "_id": "band_0070"
    },
    "band_0071": {
        "actname": "Dogwhite",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Hard Rock Band",
        "image": "",
        "_id": "band_0071"
    },
    "band_0072": {
        "actname": "Log",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Energetic Synth Rock",
        "image": "",
        "_id": "band_0072"
    },
    "band_0073": {
        "actname": "SoundMindz",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Eclectic, Funky, Fusion",
        "image": "",
        "_id": "band_0073"
    },
    "band_0074": {
        "actname": "Rippin Gorillaz",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Unstoppable Electric and Fearless",
        "image": "",
        "_id": "band_0074"
    },
    "band_0075": {
        "actname": "Tio Rojo",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Rock and Soul",
        "image": "",
        "_id": "band_0075"
    },
    "band_0076": {
        "actname": "Muddy River Drifters",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Old-Time, Traditional, String Band",
        "image": "",
        "_id": "band_0076"
    },
    "band_0077": {
        "actname": "TOKYO TRAMPS",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Original Blues/Rock Unit",
        "image": "",
        "_id": "band_0077"
    },
    "band_0078": {
        "actname": "Kungíz",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun, Up-Beat, Danceable",
        "image": "",
        "_id": "band_0078"
    },
    "band_0079": {
        "actname": "Boston Ostinatos",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "World, Classical, Jazz",
        "image": "",
        "_id": "band_0079"
    },
    "band_0080": {
        "actname": "Klez Encounters",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Traditional Klezmer.",
        "image": "",
        "_id": "band_0080"
    },
    "band_0081": {
        "actname": "Caboose",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Indie Folk Music",
        "image": "",
        "_id": "band_0081"
    },
    "band_0082": {
        "actname": "Late Start",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Three-Person Guitar Band",
        "image": "",
        "_id": "band_0082"
    },
    "band_0083": {
        "actname": "The Angelbreakers",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Dance-Punk Trio",
        "image": "",
        "_id": "band_0083"
    },
    "band_0084": {
        "actname": "Ricardo Barraza",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun Acoustic Covers",
        "image": "",
        "_id": "band_0084"
    },
    "band_0085": {
        "actname": "Danny Schwindinger",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jaunty, Acoustic, Relatable",
        "image": "",
        "_id": "band_0085"
    },
    "band_0086": {
        "actname": "Vices Inc",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun Music Fun",
        "image": "",
        "_id": "band_0086"
    },
    "band_0087": {
        "actname": "Broadband",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "All-Treble A Cappella",
        "image": "",
        "_id": "band_0087"
    },
    "band_0088": {
        "actname": "Hatchback",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Rock Classics Yeah",
        "image": "",
        "_id": "band_0088"
    },
    "band_0089": {
        "actname": "Sal de la Isla",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Boricua. Faithful. Acoustic.",
        "image": "",
        "_id": "band_0089"
    },
    "band_0090": {
        "actname": "The Midcentury Modern Quintet",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Small Jazz Combo",
        "image": "",
        "_id": "band_0090"
    },
    "band_0091": {
        "actname": "Station Street",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Brookline Jazz Band",
        "image": "",
        "_id": "band_0091"
    },
    "band_0092": {
        "actname": "Washington Square Jazz Quartet",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jazz Swing Standards",
        "image": "",
        "_id": "band_0092"
    },
    "band_0093": {
        "actname": "Nasuree Van Gelder Band",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Powerful, Authentic, Energetic",
        "image": "",
        "_id": "band_0093"
    },
    "band_0094": {
        "actname": "Raine and Jade",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Cool and Musically Adventurous",
        "image": "",
        "_id": "band_0094"
    },
    "band_0095": {
        "actname": "Amilia and the Crispy Nuggets",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Crispy Fun Vibes",
        "image": "",
        "_id": "band_0095"
    },
    "band_0096": {
        "actname": "Almost Friday",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Upbeat Rock Pop",
        "image": "",
        "_id": "band_0096"
    },
    "band_0097": {
        "actname": "Jay Ottaway and the Ramble",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Acoustic-Based Americana",
        "image": "",
        "_id": "band_0097"
    },
    "band_0098": {
        "actname": "PlantHouse",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Fun, Prepared, Variety",
        "image": "",
        "_id": "band_0098"
    },
    "band_0099": {
        "actname": "The Hip Replacements",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Jazz",
        "image": "",
        "_id": "band_0099"
    },
    "band_0100": {
        "actname": "Luis Reyes Quintet",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Progressive Contemporary Jazz",
        "image": "",
        "_id": "band_0100"
    },
    "band_0101": {
        "actname": "Abby Volta",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Alt Gothic Rock",
        "image": "",
        "_id": "band_0101"
    },
    "band_0102": {
        "actname": "On Tap",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Energetic Rock Covers",
        "image": "",
        "_id": "band_0102"
    },
    "band_0103": {
        "actname": "Brookline Symphony Orchestra",
        "genre": "",
        "other_genre": "",
        "website": "",
        "facebook": "",
        "instagram": "",
        "bandcamp": "",
        "spotify": "",
        "apple": "",
        "otheronline": "",
        "description": "Classical Chamber Music",
        "image": "",
        "_id": "band_0103"
    }
};

const porches = {
    "porch_0001": {
        "address": "86 Verndale Street, Brookline, MA",
        "lat": "42.3465537",
        "lng": "-71.1326408",
        "porchnum": "",
        "_id": "porch_0001"
    },
    "porch_0002": {
        "address": "58 Verndale Street, Brookline, MA",
        "lat": "42.3471777",
        "lng": "-71.1315183",
        "porchnum": "",
        "_id": "porch_0002"
    },
    "porch_0003": {
        "address": "81 Verndale Street, Brookline, MA",
        "lat": "42.3469333",
        "lng": "-71.1328253",
        "porchnum": "",
        "_id": "porch_0003"
    },
    "porch_0004": {
        "address": "32 Russell Street, Brookline, MA",
        "lat": "42.3465044",
        "lng": "-71.1298690",
        "porchnum": "",
        "_id": "porch_0004"
    },
    "porch_0005": {
        "address": "45 Russell Street, Brookline, MA",
        "lat": "42.3464250",
        "lng": "-71.1306758",
        "porchnum": "",
        "_id": "porch_0005"
    },
    "porch_0006": {
        "address": "69 Columbia Street, Brookline, MA",
        "lat": "42.3458287",
        "lng": "-71.1309023",
        "porchnum": "",
        "_id": "porch_0006"
    },
    "porch_0007": {
        "address": "96 Winchester Street, Brookline, MA",
        "lat": "42.3432817",
        "lng": "-71.1282074",
        "porchnum": "",
        "_id": "porch_0007"
    },
    "porch_0008": {
        "address": "112 Centre Street, Brookline, MA",
        "lat": "42.3440291",
        "lng": "-71.1276237",
        "porchnum": "",
        "_id": "porch_0008"
    },
    "porch_0009": {
        "address": "162 Mason Terrace, Brookline, MA",
        "lat": "42.3426495",
        "lng": "-71.1292937",
        "porchnum": "",
        "_id": "porch_0009"
    },
    "porch_0010": {
        "address": "1550 Beacon Street, Brookline MA",
        "lat": "42.3400357",
        "lng": "-71.1317256",
        "porchnum": "",
        "_id": "porch_0010"
    },
    "porch_0011": {
        "address": "297 Mason Terrace, Brookline, MA",
        "lat": "42.3449023",
        "lng": "-71.1344991",
        "porchnum": "",
        "_id": "porch_0011"
    },
    "porch_0012": {
        "address": "188 Winchester Street #2, Brookline, MA",
        "lat": "42.3448096",
        "lng": "-71.1318970",
        "porchnum": "",
        "_id": "porch_0012"
    },
    "porch_0013": {
        "address": "5 Verndale Street, Brookline, MA",
        "lat": "42.3484240",
        "lng": "-71.1299959",
        "porchnum": "",
        "_id": "porch_0013"
    },
    "porch_0014": {
        "address": "1398 Beacon Street, Brookline, MA",
        "lat": "42.3415351",
        "lng": "-71.1249139",
        "porchnum": "",
        "_id": "porch_0014"
    },
    "porch_0015": {
        "address": "197 Fuller Street, Brookline, MA",
        "lat": "42.3500443",
        "lng": "-71.1245242",
        "porchnum": "",
        "_id": "porch_0015"
    },
    "porch_0016": {
        "address": "1 Osborne Road, Brookline, MA",
        "lat": "42.3498400",
        "lng": "-71.1236339",
        "porchnum": "",
        "_id": "porch_0016"
    },
    "porch_0017": {
        "address": "41 Osborne Road, Brookline, MA",
        "lat": "42.3495128",
        "lng": "-71.1219211",
        "porchnum": "",
        "_id": "porch_0017"
    },
    "porch_0018": {
        "address": "43 Abbottsford Road, Brookline, MA",
        "lat": "42.3495013",
        "lng": "-71.1232345",
        "porchnum": "",
        "_id": "porch_0018"
    },
    "porch_0019": {
        "address": "111 Babcock Street, Brookline, MA",
        "lat": "42.3467940",
        "lng": "-71.1211435",
        "porchnum": "",
        "_id": "porch_0019"
    },
    "porch_0020": {
        "address": "73 Fuller Street, Brookline, MA",
        "lat": "42.3458963",
        "lng": "-71.1264291",
        "porchnum": "",
        "_id": "porch_0020"
    },
    "porch_0021": {
        "address": "7 Griggs Terrace, Brookline, MA",
        "lat": "42.3395514",
        "lng": "-71.1261049",
        "porchnum": "",
        "_id": "porch_0021"
    },
    "porch_0022": {
        "address": "14 Griggs Terrace, Brookline, MA",
        "lat": "42.3396444",
        "lng": "-71.1266059",
        "porchnum": "",
        "_id": "porch_0022"
    },
    "porch_0023": {
        "address": "56 Griggs Road, Brookline, MA",
        "lat": "42.3387892",
        "lng": "-71.1278226",
        "porchnum": "",
        "_id": "porch_0023"
    },
    "porch_0024": {
        "address": "64 University Road, Brookline, MA",
        "lat": "42.3380793",
        "lng": "-71.1332250",
        "porchnum": "",
        "_id": "porch_0024"
    },
    "porch_0025": {
        "address": "23 Harris Street, Brookline, MA",
        "lat": "42.3383877",
        "lng": "-71.1226366",
        "porchnum": "",
        "_id": "porch_0025"
    },
    "porch_0026": {
        "address": "12 Greenough Street, Brookline, MA",
        "lat": "42.3349863",
        "lng": "-71.1252355",
        "porchnum": "",
        "_id": "porch_0026"
    },
    "porch_0027": {
        "address": "37 Stanton Road, Brookline, MA",
        "lat": "42.3343389",
        "lng": "-71.1255997",
        "porchnum": "",
        "_id": "porch_0027"
    },
    "porch_0028": {
        "address": "85 Stanton Road, Brookline, MA",
        "lat": "42.3350528",
        "lng": "-71.1277027",
        "porchnum": "",
        "_id": "porch_0028"
    },
    "porch_0029": {
        "address": "382 Walnut Street, Brookline, MA",
        "lat": "42.3271453",
        "lng": "-71.1306551",
        "porchnum": "",
        "_id": "porch_0029"
    },
    "porch_0030": {
        "address": "32 Kennard Road, Brookline, MA",
        "lat": "42.3285245",
        "lng": "-71.1280478",
        "porchnum": "",
        "_id": "porch_0030"
    },
    "porch_0031": {
        "address": "33 Weybridge Lane, Brookline, MA",
        "lat": "42.3364701",
        "lng": "-71.1265116",
        "porchnum": "",
        "_id": "porch_0031"
    },
    "porch_0032": {
        "address": "21 Weybridge Road, Brookline, MA",
        "lat": "42.3357137",
        "lng": "-71.1258895",
        "porchnum": "",
        "_id": "porch_0032"
    },
    "porch_0033": {
        "address": "100 Tappan Street, Brookline, MA",
        "lat": "42.3325902",
        "lng": "-71.1305424",
        "porchnum": "",
        "_id": "porch_0033"
    },
    "porch_0034": {
        "address": "58 Davis Avenue, Brookline, MA",
        "lat": "42.3320348",
        "lng": "-71.1213534",
        "porchnum": "",
        "_id": "porch_0034"
    },
    "porch_0035": {
        "address": "68 Davis Avenue, Brookline, MA",
        "lat": "42.3319221",
        "lng": "-71.1218049",
        "porchnum": "",
        "_id": "porch_0035"
    },
    "porch_0036": {
        "address": "135 Davis Avenue, Brookline, MA",
        "lat": "42.3319074",
        "lng": "-71.1248283",
        "porchnum": "",
        "_id": "porch_0036"
    },
    "porch_0037": {
        "address": "361 Washington Street, Brookline, MA",
        "lat": "42.3346378",
        "lng": "-71.1213843",
        "porchnum": "",
        "_id": "porch_0037"
    },
    "porch_0038": {
        "address": "30 St. Paul Street, Brookline, MA",
        "lat": "42.3379236",
        "lng": "-71.1189597",
        "porchnum": "",
        "_id": "porch_0038"
    },
    "porch_0039": {
        "address": "Franklin St & Rice St, Brookline, MA",
        "lat": "42.3274",
        "lng": "-71.1232",
        "porchnum": "",
        "_id": "porch_0039"
    },
    "porch_0040": {
        "address": "1485 Beacon Street, Brookline, MA",
        "lat": "42.3396626",
        "lng": "-71.1285874",
        "porchnum": "",
        "_id": "porch_0040"
    },
    "porch_0041": {
        "address": "40 Aspinwall Avenue, Brookline, MA",
        "lat": "42.3369556",
        "lng": "-71.1202631",
        "porchnum": "",
        "_id": "porch_0041"
    },
    "porch_0042": {
        "address": "102 Stearns Road, Brookline, MA",
        "lat": "42.3398186",
        "lng": "-71.1162265",
        "porchnum": "",
        "_id": "porch_0042"
    },
    "porch_0043": {
        "address": "89 St. Paul Street, Brookline, MA",
        "lat": "42.3397062",
        "lng": "-71.1175443",
        "porchnum": "",
        "_id": "porch_0043"
    },
    "porch_0044": {
        "address": "700 Brookline Ave, Brookline MA 02445",
        "lat": "42.3321471",
        "lng": "-71.1140429",
        "porchnum": "",
        "_id": "porch_0044"
    },
    "porch_0045": {
        "address": "38 Cumberland Ave, Brookline, MA",
        "lat": "42.3273944",
        "lng": "-71.1180181",
        "porchnum": "",
        "_id": "porch_0045"
    },
    "porch_0046": {
        "address": "73 Linden Street, Brookline, MA",
        "lat": "42.3341163",
        "lng": "-71.1152321",
        "porchnum": "",
        "_id": "porch_0046"
    },
    "porch_0047": {
        "address": "66 Perry Street, Brookline, MA",
        "lat": "42.3377834",
        "lng": "-71.1174915",
        "porchnum": "",
        "_id": "porch_0047"
    },
    "porch_0048": {
        "address": "62 Toxteth Street, Brookline, MA",
        "lat": "42.3374329",
        "lng": "-71.1161877",
        "porchnum": "",
        "_id": "porch_0048"
    },
    "porch_0049": {
        "address": "81 Toxteth Street, Brookline, MA",
        "lat": "42.3379247",
        "lng": "-71.1154823",
        "porchnum": "",
        "_id": "porch_0049"
    },
    "porch_0050": {
        "address": "38 Harrison Street, Brookline, MA",
        "lat": "42.3377090",
        "lng": "-71.1151727",
        "porchnum": "",
        "_id": "porch_0050"
    },
    "porch_0051": {
        "address": "39 Eliot Crescent #3, Brookline, MA",
        "lat": "42.3272773",
        "lng": "-71.1464427",
        "porchnum": "",
        "_id": "porch_0051"
    },
    "porch_0052": {
        "address": "130 Dean Road, Brookline, MA",
        "lat": "42.3338317",
        "lng": "-71.1444625",
        "porchnum": "",
        "_id": "porch_0052"
    },
    "porch_0053": {
        "address": "256 Tappan Street, Brookline, MA",
        "lat": "42.3347001",
        "lng": "-71.1364193",
        "porchnum": "",
        "_id": "porch_0053"
    },
    "porch_0054": {
        "address": "266 Clark Road, Brookline, MA",
        "lat": "42.3339564",
        "lng": "-71.1382138",
        "porchnum": "",
        "_id": "porch_0054"
    },
    "porch_0055": {
        "address": "285 Clark Road, Brookline, MA",
        "lat": "42.3346770",
        "lng": "-71.1386025",
        "porchnum": "",
        "_id": "porch_0055"
    },
    "porch_0056": {
        "address": "93 Evans Road, Brookline, MA",
        "lat": "42.3404626",
        "lng": "-71.1413761",
        "porchnum": "",
        "_id": "porch_0056"
    },
    "porch_0057": {
        "address": "88 Williston Road, Brookline, MA",
        "lat": "42.3408756",
        "lng": "-71.1413188",
        "porchnum": "",
        "_id": "porch_0057"
    },
    "porch_0058": {
        "address": "808 Washington Street, Brookline, MA",
        "lat": "42.3415942",
        "lng": "-71.1394497",
        "porchnum": "",
        "_id": "porch_0058"
    },
    "porch_0059": {
        "address": "1773 Beacon Street, Brookline, MA",
        "lat": "42.3371218",
        "lng": "-71.1420446",
        "porchnum": "",
        "_id": "porch_0059"
    }
};

const gigs = {
    "gig_00001": {
        "bandid": "band_0001",
        "porchid": "porch_0001",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00001"
    },
    "gig_00002": {
        "bandid": "band_0002",
        "porchid": "porch_0002",
        "starthour": "16",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00002"
    },
    "gig_00003": {
        "bandid": "band_0003",
        "porchid": "porch_0003",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00003"
    },
    "gig_00004": {
        "bandid": "band_0004",
        "porchid": "porch_0003",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00004"
    },
    "gig_00005": {
        "bandid": "band_0005",
        "porchid": "porch_0003",
        "starthour": "17",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00005"
    },
    "gig_00006": {
        "bandid": "band_0006",
        "porchid": "porch_0003",
        "starthour": "17",
        "startminute": "45",
        "duration": "45",
        "_id": "gig_00006"
    },
    "gig_00007": {
        "bandid": "band_0007",
        "porchid": "porch_0004",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00007"
    },
    "gig_00008": {
        "bandid": "band_0008",
        "porchid": "porch_0004",
        "starthour": "15",
        "startminute": "15",
        "duration": "105",
        "_id": "gig_00008"
    },
    "gig_00009": {
        "bandid": "band_0009",
        "porchid": "porch_0005",
        "starthour": "14",
        "startminute": "00",
        "duration": "75",
        "_id": "gig_00009"
    },
    "gig_00010": {
        "bandid": "band_0010",
        "porchid": "porch_0005",
        "starthour": "17",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00010"
    },
    "gig_00011": {
        "bandid": "band_0011",
        "porchid": "porch_0006",
        "starthour": "11",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00011"
    },
    "gig_00012": {
        "bandid": "band_0012",
        "porchid": "porch_0006",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00012"
    },
    "gig_00013": {
        "bandid": "band_0013",
        "porchid": "porch_0007",
        "starthour": "12",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00013"
    },
    "gig_00014": {
        "bandid": "band_0014",
        "porchid": "porch_0008",
        "starthour": "14",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00014"
    },
    "gig_00015": {
        "bandid": "band_0015",
        "porchid": "porch_0009",
        "starthour": "13",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00015"
    },
    "gig_00016": {
        "bandid": "band_0016",
        "porchid": "porch_0010",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00016"
    },
    "gig_00017": {
        "bandid": "band_0017",
        "porchid": "porch_0010",
        "starthour": "13",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00017"
    },
    "gig_00018": {
        "bandid": "band_0018",
        "porchid": "porch_0011",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00018"
    },
    "gig_00019": {
        "bandid": "band_0019",
        "porchid": "porch_0012",
        "starthour": "12",
        "startminute": "45",
        "duration": "60",
        "_id": "gig_00019"
    },
    "gig_00020": {
        "bandid": "band_0020",
        "porchid": "porch_0012",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00020"
    },
    "gig_00021": {
        "bandid": "band_0021",
        "porchid": "porch_0013",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00021"
    },
    "gig_00022": {
        "bandid": "band_0022",
        "porchid": "porch_0014",
        "starthour": "13",
        "startminute": "45",
        "duration": "60",
        "_id": "gig_00022"
    },
    "gig_00023": {
        "bandid": "band_0023",
        "porchid": "porch_0014",
        "starthour": "15",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00023"
    },
    "gig_00024": {
        "bandid": "band_0024",
        "porchid": "porch_0015",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00024"
    },
    "gig_00025": {
        "bandid": "band_0025",
        "porchid": "porch_0016",
        "starthour": "11",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00025"
    },
    "gig_00026": {
        "bandid": "band_0026",
        "porchid": "porch_0016",
        "starthour": "13",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00026"
    },
    "gig_00027": {
        "bandid": "band_0027",
        "porchid": "porch_0017",
        "starthour": "13",
        "startminute": "30",
        "duration": "45",
        "_id": "gig_00027"
    },
    "gig_00028": {
        "bandid": "band_0028",
        "porchid": "porch_0018",
        "starthour": "14",
        "startminute": "15",
        "duration": "45",
        "_id": "gig_00028"
    },
    "gig_00029": {
        "bandid": "band_0029",
        "porchid": "porch_0018",
        "starthour": "15",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00029"
    },
    "gig_00030": {
        "bandid": "band_0030",
        "porchid": "porch_0018",
        "starthour": "16",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00030"
    },
    "gig_00031": {
        "bandid": "band_0031",
        "porchid": "porch_0019",
        "starthour": "13",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00031"
    },
    "gig_00032": {
        "bandid": "band_0032",
        "porchid": "porch_0019",
        "starthour": "14",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00032"
    },
    "gig_00033": {
        "bandid": "band_0033",
        "porchid": "porch_0020",
        "starthour": "12",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00033"
    },
    "gig_00034": {
        "bandid": "band_0034",
        "porchid": "porch_0020",
        "starthour": "12",
        "startminute": "45",
        "duration": "90",
        "_id": "gig_00034"
    },
    "gig_00035": {
        "bandid": "band_0035",
        "porchid": "porch_0020",
        "starthour": "14",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00035"
    },
    "gig_00036": {
        "bandid": "band_0036",
        "porchid": "porch_0021",
        "starthour": "11",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00036"
    },
    "gig_00037": {
        "bandid": "band_0037",
        "porchid": "porch_0021",
        "starthour": "16",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00037"
    },
    "gig_00038": {
        "bandid": "band_0038",
        "porchid": "porch_0022",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00038"
    },
    "gig_00039": {
        "bandid": "band_0039",
        "porchid": "porch_0022",
        "starthour": "15",
        "startminute": "00",
        "duration": "90",
        "_id": "gig_00039"
    },
    "gig_00040": {
        "bandid": "band_0040",
        "porchid": "porch_0023",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00040"
    },
    "gig_00041": {
        "bandid": "band_0041",
        "porchid": "porch_0024",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00041"
    },
    "gig_00042": {
        "bandid": "band_0042",
        "porchid": "porch_0025",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00042"
    },
    "gig_00043": {
        "bandid": "band_0043",
        "porchid": "porch_0025",
        "starthour": "16",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00043"
    },
    "gig_00044": {
        "bandid": "band_0044",
        "porchid": "porch_0025",
        "starthour": "17",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00044"
    },
    "gig_00045": {
        "bandid": "band_0045",
        "porchid": "porch_0026",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00045"
    },
    "gig_00046": {
        "bandid": "band_0046",
        "porchid": "porch_0027",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00046"
    },
    "gig_00047": {
        "bandid": "band_0047",
        "porchid": "porch_0027",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00047"
    },
    "gig_00048": {
        "bandid": "band_0048",
        "porchid": "porch_0027",
        "starthour": "16",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00048"
    },
    "gig_00049": {
        "bandid": "band_0049",
        "porchid": "porch_0028",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00049"
    },
    "gig_00050": {
        "bandid": "band_0050",
        "porchid": "porch_0028",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00050"
    },
    "gig_00051": {
        "bandid": "band_0051",
        "porchid": "porch_0028",
        "starthour": "16",
        "startminute": "00",
        "duration": "45",
        "_id": "gig_00051"
    },
    "gig_00052": {
        "bandid": "band_0052",
        "porchid": "porch_0029",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00052"
    },
    "gig_00053": {
        "bandid": "band_0053",
        "porchid": "porch_0029",
        "starthour": "14",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00053"
    },
    "gig_00054": {
        "bandid": "band_0054",
        "porchid": "porch_0029",
        "starthour": "15",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00054"
    },
    "gig_00055": {
        "bandid": "band_0055",
        "porchid": "porch_0030",
        "starthour": "15",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00055"
    },
    "gig_00056": {
        "bandid": "band_0056",
        "porchid": "porch_0031",
        "starthour": "12",
        "startminute": "15",
        "duration": "90",
        "_id": "gig_00056"
    },
    "gig_00057": {
        "bandid": "band_0057",
        "porchid": "porch_0031",
        "starthour": "14",
        "startminute": "00",
        "duration": "90",
        "_id": "gig_00057"
    },
    "gig_00058": {
        "bandid": "band_0058",
        "porchid": "porch_0032",
        "starthour": "15",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00058"
    },
    "gig_00059": {
        "bandid": "band_0059",
        "porchid": "porch_0033",
        "starthour": "13",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00059"
    },
    "gig_00060": {
        "bandid": "band_0060",
        "porchid": "porch_0033",
        "starthour": "15",
        "startminute": "15",
        "duration": "30",
        "_id": "gig_00060"
    },
    "gig_00061": {
        "bandid": "band_0061",
        "porchid": "porch_0034",
        "starthour": "12",
        "startminute": "00",
        "duration": "90",
        "_id": "gig_00061"
    },
    "gig_00062": {
        "bandid": "band_0062",
        "porchid": "porch_0035",
        "starthour": "14",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00062"
    },
    "gig_00063": {
        "bandid": "band_0063",
        "porchid": "porch_0036",
        "starthour": "13",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00063"
    },
    "gig_00064": {
        "bandid": "band_0064",
        "porchid": "porch_0036",
        "starthour": "15",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00064"
    },
    "gig_00065": {
        "bandid": "band_0065",
        "porchid": "porch_0037",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00065"
    },
    "gig_00066": {
        "bandid": "band_0066",
        "porchid": "porch_0038",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00066"
    },
    "gig_00067": {
        "bandid": "band_0067",
        "porchid": "porch_0039",
        "starthour": "16",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00067"
    },
    "gig_00068": {
        "bandid": "band_0068",
        "porchid": "porch_0040",
        "starthour": "13",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00068"
    },
    "gig_00069": {
        "bandid": "band_0069",
        "porchid": "porch_0040",
        "starthour": "13",
        "startminute": "45",
        "duration": "30",
        "_id": "gig_00069"
    },
    "gig_00070": {
        "bandid": "band_0070",
        "porchid": "porch_0040",
        "starthour": "14",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00070"
    },
    "gig_00071": {
        "bandid": "band_0071",
        "porchid": "porch_0040",
        "starthour": "15",
        "startminute": "15",
        "duration": "30",
        "_id": "gig_00071"
    },
    "gig_00072": {
        "bandid": "band_0072",
        "porchid": "porch_0040",
        "starthour": "16",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00072"
    },
    "gig_00073": {
        "bandid": "band_0073",
        "porchid": "porch_0041",
        "starthour": "15",
        "startminute": "30",
        "duration": "30",
        "_id": "gig_00073"
    },
    "gig_00074": {
        "bandid": "band_0074",
        "porchid": "porch_0041",
        "starthour": "16",
        "startminute": "15",
        "duration": "30",
        "_id": "gig_00074"
    },
    "gig_00075": {
        "bandid": "band_0075",
        "porchid": "porch_0042",
        "starthour": "12",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00075"
    },
    "gig_00076": {
        "bandid": "band_0076",
        "porchid": "porch_0043",
        "starthour": "15",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00076"
    },
    "gig_00077": {
        "bandid": "band_0077",
        "porchid": "porch_0044",
        "starthour": "13",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00077"
    },
    "gig_00078": {
        "bandid": "band_0078",
        "porchid": "porch_0044",
        "starthour": "14",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00078"
    },
    "gig_00079": {
        "bandid": "band_0079",
        "porchid": "porch_0044",
        "starthour": "16",
        "startminute": "00",
        "duration": "30",
        "_id": "gig_00079"
    },
    "gig_00080": {
        "bandid": "band_0080",
        "porchid": "porch_0045",
        "starthour": "13",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00080"
    },
    "gig_00081": {
        "bandid": "band_0081",
        "porchid": "porch_0046",
        "starthour": "12",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00081"
    },
    "gig_00082": {
        "bandid": "band_0082",
        "porchid": "porch_0046",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00082"
    },
    "gig_00083": {
        "bandid": "band_0083",
        "porchid": "porch_0046",
        "starthour": "16",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00083"
    },
    "gig_00084": {
        "bandid": "band_0084",
        "porchid": "porch_0047",
        "starthour": "14",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00084"
    },
    "gig_00085": {
        "bandid": "band_0085",
        "porchid": "porch_0048",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00085"
    },
    "gig_00086": {
        "bandid": "band_0086",
        "porchid": "porch_0049",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00086"
    },
    "gig_00087": {
        "bandid": "band_0087",
        "porchid": "porch_0050",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00087"
    },
    "gig_00088": {
        "bandid": "band_0088",
        "porchid": "porch_0050",
        "starthour": "16",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00088"
    },
    "gig_00089": {
        "bandid": "band_0089",
        "porchid": "porch_0051",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00089"
    },
    "gig_00090": {
        "bandid": "band_0090",
        "porchid": "porch_0051",
        "starthour": "14",
        "startminute": "45",
        "duration": "60",
        "_id": "gig_00090"
    },
    "gig_00091": {
        "bandid": "band_0091",
        "porchid": "porch_0051",
        "starthour": "16",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00091"
    },
    "gig_00092": {
        "bandid": "band_0092",
        "porchid": "porch_0052",
        "starthour": "14",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00092"
    },
    "gig_00093": {
        "bandid": "band_0093",
        "porchid": "porch_0052",
        "starthour": "15",
        "startminute": "45",
        "duration": "60",
        "_id": "gig_00093"
    },
    "gig_00094": {
        "bandid": "band_0094",
        "porchid": "porch_0053",
        "starthour": "15",
        "startminute": "30",
        "duration": "60",
        "_id": "gig_00094"
    },
    "gig_00095": {
        "bandid": "band_0095",
        "porchid": "porch_0054",
        "starthour": "14",
        "startminute": "15",
        "duration": "30",
        "_id": "gig_00095"
    },
    "gig_00096": {
        "bandid": "band_0096",
        "porchid": "porch_0054",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00096"
    },
    "gig_00097": {
        "bandid": "band_0097",
        "porchid": "porch_0055",
        "starthour": "16",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00097"
    },
    "gig_00098": {
        "bandid": "band_0098",
        "porchid": "porch_0056",
        "starthour": "13",
        "startminute": "00",
        "duration": "120",
        "_id": "gig_00098"
    },
    "gig_00099": {
        "bandid": "band_0099",
        "porchid": "porch_0057",
        "starthour": "12",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00099"
    },
    "gig_00100": {
        "bandid": "band_0100",
        "porchid": "porch_0057",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00100"
    },
    "gig_00101": {
        "bandid": "band_0101",
        "porchid": "porch_0058",
        "starthour": "15",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00101"
    },
    "gig_00102": {
        "bandid": "band_0102",
        "porchid": "porch_0058",
        "starthour": "16",
        "startminute": "15",
        "duration": "60",
        "_id": "gig_00102"
    },
    "gig_00103": {
        "bandid": "band_0103",
        "porchid": "porch_0059",
        "starthour": "14",
        "startminute": "00",
        "duration": "60",
        "_id": "gig_00103"
    }
};
